---
abstract: unknown
author:
  - 'Ben Bullock <bkb@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.9, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-CGI-External
no_index:
  directory:
    - t
    - inc
requires:
  IO::Uncompress::Gunzip: '0'
  IPC::Run3: '0'
  Test::More: '0'
  perl: '5.006'
resources:
  bugtracker: https://github.com/benkasminbullock/test-cgi-external/issues
  repository: git://github.com/benkasminbullock/test-cgi-external.git
version: 0.00_02
